# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sms/sms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsms/sms.proto\x12\x05proto\"\"\n\x03Msg\x12\r\n\x05phone\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\"\n\x03Res\x12\x0e\n\x06result\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2%\n\x03SMS\x12\x1e\n\x04Send\x12\n.proto.Msg\x1a\n.proto.ResB\x0fZ\r./proto;protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sms.sms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\r./proto;proto'
  _MSG._serialized_start=24
  _MSG._serialized_end=58
  _RES._serialized_start=60
  _RES._serialized_end=94
  _SMS._serialized_start=96
  _SMS._serialized_end=133
# @@protoc_insertion_point(module_scope)
